package x464010.teamb.srs;

import java.util.ArrayList;
import java.util.Comparator;


/**
 * Student class contains information about each of the 
 * student objects.
 * 
 * @author William Crews
 * @version 1.2				
 * @revision 1.2					Added setters and getters, toString()
 *                              	compareTo() for sorting LastName, then FirstName
 *                              	compare() for sorting studentIDs in ascending order
 * @revision 1.3	Amit Dhamija	Modified the toString() method
 */

public class Student implements Comparator<Student>, Comparable<Student>  {
	
	private int studentID;
	private String firstName;
	private String lastName;
	private String address;
	private String city;
	private String state;
	private String zip;
	private String password = null;
	ArrayList<String> courseList = new ArrayList<String>();
	
	/**
	 * Constructor
	 *
	 * @param studentID			Student ID generated by system when account is created
	 * @param firstName			Students First Name
	 * @param lastName			Students Last Name
	 * @param address			Street Address of student
	 * @param state				State, two letter code representing state
	 * @param zip				Zip code of student
	 * @param password			Password student has chosen for account 
	 */
	public Student(int studentID, String firstName, String lastName, 
	           String address, String city, String state, String zip, 
	           String password) {
		
		this.studentID = studentID;
		this.firstName = firstName;
		this.lastName = lastName;
		this.address = address;
		this.city = city;
		this.state = state;
		this.zip = zip;
		this.password = password;
		this.courseList = null;
	}
	
	public Student(String[] fileRecord) {
		
		this.studentID = Integer.parseInt(fileRecord[0]);
		this.firstName = fileRecord[1].trim();
		this.lastName = fileRecord[2].trim();
		this.address = fileRecord[3];
		this.city = fileRecord[4];
		this.state = fileRecord[5];
		this.zip = fileRecord[6];
		this.password = fileRecord[7];
	}
	
	/**
	 * Getters & Setters
	 */
	
	protected int getStudentID(){
		return studentID;
	}
	
	protected void setStudentID(int studentID){
		this.studentID = studentID;
	}
	
	protected String getPassword(){
		return password;
	}
	
	protected void setPassword(String password) {
		this.password = password;
	}
	
	protected String getFirstName() {
		return firstName;
	}
	
	protected void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	
	protected String getLastName() {
		return lastName;
	}
	
	protected void setLastName(String lastName){
		this.lastName = lastName;
	}
	
	protected String getAddress() {
		return address;
	}
	
	protected void setAddress(String address) {
		this.address = address;
	}
	
	protected String getCity() {
		return city;
	}
	
	protected void setCity(String city) {
		this.city = city;
	}
	
	protected String getState() {
		return state;
	}
	
	protected void setState(String state) {
		this.state = state;
	}
	
	protected String getZip() {
		return zip;
	}
	
	protected void setZip(String zip) {
		this.zip = zip;
	}
	
	
	public String toString() {
		return studentID + "," + firstName + ","
		       + lastName + "," + address + "," + city + "," 
		       + state + "," + zip + "," + password;
	}
	
	// Overriding the compareTo method to sort by Last Name then First Name if necessary.
	public int compareTo(Student student) {
		// compare last names
		int lastCmp = lastName.compareTo(student.lastName);
		// If last names are the same (equal to 0) then compare first names
		return(lastCmp != 0 ? lastCmp : firstName.compareTo(student.firstName));
	}
	
	// Overriding the compare method to sort by increasing studentID numbers
	public int compare(Student s1, Student s2) {
		return(s1.studentID - s2.studentID);	// Will sort in increasing studentID numbers
	}
}